# Generated by Django 3.2.9 on 2021-11-17 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, default='altr.jpg', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Cloths', 'cloths'), ('Shoes', 'shoes'), ('Games', 'games'), ('IOTs', 'iots'), ('Books', 'books')], max_length=200, null=True)),
                ('description', models.TextField(max_length=300, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, default='alternative.jpg', null=True, upload_to='')),
                ('tags', models.ManyToManyField(to='Manager.Tag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Delivered', 'delivered')], default='pending', max_length=200)),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('quentity', models.IntegerField(default=1, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.customer')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.product')),
            ],
        ),
    ]
